#!/usr/bin/env python3
"""
Generate src/provider_configs.py from config/*.yml.

The repository keeps provider configs in a deliberately small YAML subset:
top-level mappings whose values are one-level string mappings. This generator
parses that subset with the standard library so CI and local development do not
need a YAML dependency.
"""

from __future__ import annotations

import argparse
import difflib
import json
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_CONFIG_DIR = REPO_ROOT / "config"
DEFAULT_OUTPUT = REPO_ROOT / "src" / "provider_configs.py"


def parse_scalar(value: str) -> str:
    value = value.strip()
    if value.startswith("!!"):
        return ""
    if len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"'}:
        return value[1:-1]
    return value


def parse_provider_config(path: Path) -> dict[str, dict[str, str]]:
    config: dict[str, dict[str, str]] = {}
    current_section: str | None = None

    for line_number, raw_line in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
        stripped = raw_line.strip()
        if not stripped or stripped == "---" or stripped.startswith("#"):
            continue

        indent = len(raw_line) - len(raw_line.lstrip(" "))
        if indent == 0:
            key, separator, value = stripped.partition(":")
            if not separator:
                raise ValueError(f"{path}:{line_number}: expected top-level mapping")
            current_section = key.strip()
            config[current_section] = {}
            inline_value = parse_scalar(value)
            if inline_value:
                raise ValueError(f"{path}:{line_number}: top-level values must be mappings")
            continue

        if indent == 2 and current_section:
            key, separator, value = stripped.partition(":")
            if not separator:
                raise ValueError(f"{path}:{line_number}: expected nested mapping")
            config[current_section][key.strip()] = parse_scalar(value)
            continue

        raise ValueError(f"{path}:{line_number}: unsupported YAML structure")

    for section in ("type_regex", "csv_fieldnames"):
        if section not in config:
            raise ValueError(f"{path}: missing required section {section!r}")

    return config


def load_provider_configs(config_dir: Path) -> dict[str, dict[str, dict[str, str]]]:
    configs: dict[str, dict[str, dict[str, str]]] = {}
    for path in sorted(config_dir.glob("*.yml")):
        configs[path.stem] = parse_provider_config(path)

    if not configs:
        raise ValueError(f"No provider config files found in {config_dir}")

    return configs


def render_provider_configs(configs: dict[str, dict[str, dict[str, str]]]) -> str:
    rendered = json.dumps(configs, ensure_ascii=False, indent=4)
    return (
        "# -*- coding: utf-8 -*-\n"
        '"""\n'
        "Bundled provider configuration for the P2P statement parser.\n\n"
        "Generated from config/*.yml by tools/generate_provider_configs.py.\n"
        "Do not edit this file by hand.\n"
        '"""\n\n\n'
        f"PROVIDER_CONFIGS = {rendered}\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config-dir", type=Path, default=DEFAULT_CONFIG_DIR)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true", help="fail if the generated output is not up to date")
    args = parser.parse_args()

    generated = render_provider_configs(load_provider_configs(args.config_dir))

    if args.check:
        current = args.output.read_text(encoding="utf-8") if args.output.exists() else ""
        if current == generated:
            return 0

        diff = difflib.unified_diff(
            current.splitlines(keepends=True),
            generated.splitlines(keepends=True),
            fromfile=str(args.output),
            tofile=f"{args.output} (generated)",
        )
        sys.stderr.writelines(diff)
        sys.stderr.write(
            f"\n{args.output} is not up to date. Run tools/generate_provider_configs.py and commit the result.\n"
        )
        return 1

    args.output.write_text(generated, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
